# Generated by Django 4.2.15 on 2024-08-16 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.CharField(max_length=6)),
                ('matrix_map', models.CharField(default='[1,2,3,4,5,6,7,8,9]', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.CharField(max_length=6)),
                ('game_creator', models.CharField(max_length=50)),
                ('game_opponent', models.CharField(default='to-be-decided', max_length=50)),
                ('game_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tic_tac_toe.gamematrix')),
            ],
        ),
    ]
